name: Build and Testing

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:  
  UnitestPython38:
    
    name: Python3.8 Tests
    runs-on: ubuntu-latest
    # needs: None
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'pip'
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements_extra.txt
    - name: Download and Setup Resources
      run: |
        apt-get update
        apt-get install unzip -y 
        wget https://github.com/OlafenwaMoses/ImageAI/releases/download/test-resources-v3/data-datasets.zip
        wget https://github.com/OlafenwaMoses/ImageAI/releases/download/test-resources-v3/data-images.zip
        wget https://github.com/OlafenwaMoses/ImageAI/releases/download/test-resources-v3/data-videos.zip
        unzip data-datasets.zip
        unzip data-images.zip
        unzip data-videos.zip
        ls
    - name: Run Unittest
      run: |
        pytest test -vvv